
services:
  router:
    build: ./router/
    stdin_open: true
    tty: true
    ports:
      - "5050:80"
      - "5051:8080"
  #ca:
  #  build: ./CA/
  #  command: /bin/bash
  #  stdin_open: true
  #  tty: true
  #  volumes:
  #    - keys:/home/ubuntu/keys
  server:
    build: ./server/
    privileged: true
    #stdin_open: true
    #tty: true
    #volumes:
    #  - keys:/home/ubuntu/keys
    #  - ./server/scripts:/home/ubuntu/scripts
    networks:
      vpn:
        ipv4_address: "10.0.4.2"
    cap_add:
      - NET_ADMIN
  client:
    build: ./client/
    stdin_open: true
    tty: true
    networks:
      vpn:
        ipv4_address: "10.0.4.3"

networks:
  vpn:
    driver: "bridge"
    ipam:
      config:
        - subnet: "10.0.4.1/24"
          gateway: "10.0.4.1"
