

services:
  router:
    build: ./router/
    ports:
      - "5050:80"
      - "5051:8080"
  ca:
    build: ./CA/
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - keys:/home/ubuntu/keys
  server:
    build: ./server/
    command: /bin/bash
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - keys:/home/ubuntu/keys

volumes:
  keys:
      